title: "Ropat Portfolio"
description: "Portfolio de Ropat"
baseurl: ""
url: "https://ropat.art"

# Exclusions pour Jekyll
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed # Optionnel : pour minifier ton CSS
  sass_dir: _sass   # Si tu mets tes partials dans un dossier nommé _sass

# Configuration Business (pour Schema.org)
business:
  name: "Ropat"
  description: "Graphiste et directeur artistique basé à Angers, spécialisé dans l'accompagnement visuel des artistes musicaux (pochettes, visualizers, affiches) et le branding d'entreprise."
  price_range: "€€"
  address:
    city: "Angers"
    region: "Pays de la Loire"
    postal: "49000"
    country: "FR"
  geo:
    latitude: "47.478419"
    longitude: "-0.563166"
  # Email
  email: "vultur.psd@gmail.com"

  # Horaires
  opening_hours:
    - day: "Monday"
      opens: "09:00"
      closes: "18:00"
    - day: "Tuesday"
      opens: "09:00"
      closes: "18:00"
    - day: "Wednesday"
      opens: "09:00"
      closes: "18:00"
    - day: "Thursday"
      opens: "09:00"
      closes: "18:00"
    - day: "Friday"
      opens: "09:00"
      closes: "18:00"

# Réseaux sociaux
social:
  instagram: "https://www.instagram.com/9.ropat/"
  pinterest: "https://fr.pinterest.com/9ropat/"
  linkedin: "https://www.linkedin.com/in/ropat-art/"
  behance: "https://www.behance.net/ropat"
