fr:
  title: "Mes services"
  intro: "Que vous soyez un artiste, un collectif ou une marque, je propose une gamme complète de services pour donner vie à votre vision. Découvrez comment je peux vous aider à créer une identité visuelle forte et cohérente."
en:
  title: "My Services"
  intro: "Whether you're an artist, collective, or brand, I offer a comprehensive range of services to bring your vision to life. Discover how I can help you create a strong and cohesive visual identity."